name: snakemake
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aioeasywebdav=2.4.0=py38h578d9bd_1001
  - aiohttp=3.8.5=py38h01eb140_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - amply=0.1.6=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attmap=0.13.2=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - bcrypt=4.0.1=py38h0cc4f7c_1
  - boto3=1.28.57=pyhd8ed1ab_0
  - botocore=1.31.57=pyhd8ed1ab_0
  - brotli-python=1.1.0=py38h17151c0_1
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.19.1=hd590300_0
  - ca-certificates=2023.7.22=hbcca054_0
  - cachetools=5.3.1=pyhd8ed1ab_0
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.16.0=py38h6d47a40_0
  - charset-normalizer=3.2.0=pyhd8ed1ab_0
  - coin-or-cbc=2.10.10=h9002f0b_0
  - coin-or-cgl=0.60.7=h516709c_0
  - coin-or-clp=1.17.8=h1ee7a9c_0
  - coin-or-osi=0.108.8=ha2443b9_0
  - coin-or-utils=2.11.9=hee58242_0
  - coincbc=2.10.10=0_metapackage
  - colorama=0.4.6=pyhd8ed1ab_0
  - configargparse=1.7=pyhd8ed1ab_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - cryptography=41.0.4=py38hcdda232_0
  - datrie=0.8.2=py38h01eb140_7
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - docutils=0.20.1=py38h578d9bd_2
  - dpath=2.1.6=pyha770c72_0
  - dropbox=11.36.2=pyhd8ed1ab_0
  - eido=0.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.1.3=pyhd8ed1ab_0
  - filechunkio=1.8=py_2
  - frozenlist=1.4.0=py38h01eb140_1
  - ftputil=5.0.4=pyhd8ed1ab_0
  - gitdb=4.0.10=pyhd8ed1ab_0
  - gitpython=3.1.37=pyhd8ed1ab_0
  - google-api-core=2.12.0=pyhd8ed1ab_0
  - google-api-python-client=2.101.0=pyhd8ed1ab_0
  - google-auth=2.23.2=pyhca7485f_0
  - google-auth-httplib2=0.1.1=pyhd8ed1ab_0
  - google-cloud-core=2.3.3=pyhd8ed1ab_0
  - google-cloud-storage=2.11.0=pyh1a96a4e_0
  - google-crc32c=1.1.2=py38hf9d55a7_5
  - google-resumable-media=2.6.0=pyhd8ed1ab_0
  - googleapis-common-protos=1.60.0=pyhd8ed1ab_0
  - grpcio=1.58.1=py38h94a1851_0
  - httplib2=0.22.0=pyhd8ed1ab_0
  - humanfriendly=10.0=py38h578d9bd_4
  - idna=3.4=pyhd8ed1ab_0
  - importlib_resources=6.1.0=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jmespath=1.0.1=pyhd8ed1ab_0
  - jsonschema=4.19.1=pyhd8ed1ab_0
  - jsonschema-specifications=2023.7.1=pyhd8ed1ab_0
  - jupyter_core=5.3.2=py38h578d9bd_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libabseil=20230802.1=cxx17_h59595ed_0
  - libblas=3.9.0=18_linux64_openblas
  - libcblas=3.9.0=18_linux64_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_2
  - libgfortran-ng=13.2.0=h69a702a_2
  - libgfortran5=13.2.0=ha4646dd_2
  - libgomp=13.2.0=h807b86a_2
  - libgrpc=1.58.1=h30d5116_0
  - liblapack=3.9.0=18_linux64_openblas
  - liblapacke=3.9.0=18_linux64_openblas
  - libnsl=2.0.0=hd590300_1
  - libopenblas=0.3.24=pthreads_h413a1c8_0
  - libprotobuf=4.24.3=hf27288f_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.43.0=h2797004_0
  - libstdcxx-ng=13.2.0=h7e041cc_2
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=hd590300_5
  - logmuse=0.2.6=pyh8c360ce_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.3=py38h01eb140_1
  - mdurl=0.1.0=pyhd8ed1ab_0
  - multidict=6.0.4=py38h1de0b5d_0
  - nbformat=5.9.2=pyhd8ed1ab_0
  - ncurses=6.4=hcb278e6_0
  - numpy=1.24.4=py38h59b608b_0
  - oauth2client=4.1.3=py_0
  - openssl=3.1.3=hd590300_0
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=2.0.3=py38h01efb38_1
  - paramiko=3.3.1=pyhd8ed1ab_0
  - peppy=0.35.7=pyhd8ed1ab_0
  - pip=23.2.1=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - plac=1.4.0=pyhd8ed1ab_0
  - platformdirs=3.10.0=pyhd8ed1ab_0
  - pluggy=1.3.0=pyhd8ed1ab_0
  - ply=3.11=py_1
  - prettytable=3.9.0=pyhd8ed1ab_0
  - protobuf=4.24.3=py38hf14ab21_0
  - psutil=5.9.5=py38h01eb140_1
  - pulp=2.7.0=py38h578d9bd_1
  - pyasn1=0.5.0=pyhd8ed1ab_0
  - pyasn1-modules=0.3.0=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - pynacl=1.5.0=py38h01eb140_3
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pysftp=0.2.9=py_1
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=7.4.2=pyhd8ed1ab_0
  - python=3.8.17=he550d4f_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.18.0=pyhd8ed1ab_0
  - python-irodsclient=1.1.8=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.8=4_cp38
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0.1=py38h01eb140_1
  - re2=2023.03.02=h8c504da_0
  - readline=8.2=h8228510_1
  - referencing=0.30.2=pyhd8ed1ab_0
  - requests=2.31.0=pyhd8ed1ab_0
  - reretry=0.11.8=pyhd8ed1ab_0
  - rich=13.5.3=pyhd8ed1ab_0
  - rpds-py=0.10.3=py38h0cc4f7c_1
  - rsa=4.9=pyhd8ed1ab_0
  - s3transfer=0.7.0=pyhd8ed1ab_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - slacker=0.14.0=py_0
  - smart_open=6.4.0=pyhd8ed1ab_0
  - smmap=3.0.5=pyh44b312d_0
  - snakemake=7.32.4=hdfd78af_0
  - snakemake-minimal=7.32.4=pyhdfd78af_0
  - stone=3.3.1=pyhd8ed1ab_0
  - stopit=1.1.2=py_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - throttler=1.2.2=pyhd8ed1ab_0
  - tk=8.6.13=h2797004_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - toposort=1.10=pyhd8ed1ab_0
  - traitlets=5.10.1=pyhd8ed1ab_0
  - typing-extensions=4.8.0=hd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - ubiquerg=0.6.3=pyhd8ed1ab_0
  - uritemplate=4.1.1=pyhd8ed1ab_0
  - urllib3=1.26.16=pyhd8ed1ab_0
  - veracitools=0.1.3=py_0
  - wcwidth=0.2.7=pyhd8ed1ab_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - wrapt=1.15.0=py38h01eb140_1
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.9.2=py38h01eb140_0
  - yte=1.5.1=pyha770c72_2
  - zipp=3.17.0=pyhd8ed1ab_0
  - pip:
    - anndata==0.9.2
    - annoy==1.17.3
    - contourpy==1.1.1
    - cycler==0.12.0
    - cython==3.0.3
    - fonttools==4.43.0
    - h5py==3.9.0
    - imageio==2.31.5
    - importlib-metadata==6.8.0
    - joblib==1.3.2
    - kiwisolver==1.4.5
    - lazy-loader==0.3
    - llvmlite==0.41.0
    - matplotlib==3.7.3
    - natsort==8.4.0
    - networkx==3.1
    - numba==0.58.0
    - patsy==0.5.3
    - pillow==10.0.1
    - pynndescent==0.5.10
    - pywavelets==1.4.1
    - scanpy==1.9.5
    - scikit-image==0.21.0
    - scikit-learn==1.3.1
    - scipy==1.10.1
    - scrublet==0.2.3
    - seaborn==0.13.0
    - session-info==1.0.0
    - statsmodels==0.14.0
    - stdlib-list==0.9.0
    - tbb==2021.10.0
    - threadpoolctl==3.2.0
    - tifffile==2023.7.10
    - tqdm==4.66.1
    - umap-learn==0.5.4
prefix: /data/homezvol3/erebboah/miniconda3/envs/snakemake
